services:
  blocktalk_backend:
    build: ./backend/
    ports: 
      - "8080:8080"
    volumes:
      - ./backend/:/app
    command: ["air"]
    depends_on:
      - blocktalk_database
    env_file:
      - .env
    networks:
      - taher

  blocktalk_database:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taher

  blocktalk_frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - taher

  blocktalk_migrate:
    image: migrate/migrate
    depends_on:
      - blocktalk_database
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@database:5432/postgres?sslmode=disable"
      ]
    command: ["up"]
    networks:
      - taher

volumes:
  postgres_data:

networks:
  taher:
    external: true
